### ISSUE TITLE
Implement contraction hierarchies

### ISSUE THREAD

**Issue by agouge** [agouge/Java-Network-Analyzer#6]
To try to speed up shortest path calculations, we need to look into using [contraction hierarchies](http://en.wikipedia.org/wiki/Contraction_hierarchies) (CH) coupled with an appropriate bidirectional Dijkstra search algorithm.
### Other Java Implementations

Note that there is already a [CH implementation](https://github.com/graphhopper/graphhopper/blob/master/src/main/java/com/graphhopper/routing/ch/PrepareContractionHierarchies.java) in GraphHopper but from what I can understand, it does not look easily adaptable to calculating centrality.

There also seems to be a [CH implementation](http://opentripplanner.org/javadoc/org/opentripplanner/routing/contraction/ContractionHierarchy.html) in OpenTripPlanner but I haven't really studied it.
### Plan of attack

I think the easiest method would be to start by watching lessons [6](http://ad-teaching.informatik.uni-freiburg.de/route-planning-ss2012/get-video.php?file=lecture-6) and [7](http://ad-teaching.informatik.uni-freiburg.de/route-planning-ss2012/get-video.php?file=lecture-7) from the [Efficient Route Planning](http://ad-wiki.informatik.uni-freiburg.de/teaching/EfficientRoutePlanningSS2012) course of the University of Freiburg. I could then implement my own version of CHs. Of course I will need to decide on #3 before I start the implementation.

@ebocher

**Comment by agouge** [comment]
### Original thesis

The main source of information is the [Fast and Exact Route Planning](http://algo2.iti.kit.edu/routeplanning.php) research project of the Institut für Theoretische Informatik, Algorithmik II. Download Robert Geisberger's thesis [Contraction Hierarchies: Faster and Simpler
Hierarchical Routing in Road Networks](http://algo2.iti.kit.edu/documents/routeplanning/geisberger_dipl.pdf).

### C++ implementations
- [MoNav](https://code.google.com/p/monav/) - desktop and mobile applications. (See Christian Vetter's [thesis](https://monav.googlecode.com/files/thesis.pdf).)
- [Open Source Routing Machine](http://project-osrm.org/) (OSRM) - server code.

Both of these use OpenStreetMap (OSM) data.

**Comment by karussell** [comment]
Be aware of the AGPL implications from OSRM. That was also the reason why I couldn't look at OSRM. And my implementation of CH took relatively long + the preparation is still a lot slower than the numbers in their papers.
